#

include:
  - /base_azure_db_stage.yml
  - /base_create_namespace_stage.yml
  - /base_delete_useless_k8s_ns_stage.yml
  - /base_deploy_app_chart_stage.yml
  - /base_deploy_kosko_stage.yml
  - /base_docker_helm_image_stage.yml
  - /base_docker_kubectl_image_stage.yml
  - /base_notify_github_stage.yml
  - /base_register_stage.yml
  - /base_semantic_release_stage.yml
  - /base_trigger_stage.yml
  - /base_yarn_stage.yml

#

workflow:
  rules:
    # Skip GitHub pull requests pipelines
    - if: "$CI_PIPELINE_SOURCE == 'external_pull_request_event'"
      when: never
    # Skip release commits
    - if: $CI_COMMIT_MESSAGE =~ /^chore\(release\)/ && $CI_COMMIT_TAG == null
      when: never
    # Otherwise include the job and set to run normally
    - when: always

#

stages:
  - Install
  - Quality check
  - Build
  - Registration
  - Release
  - Deploy

#

variables:
  GIT_DEPTH: 5
  GIT_STRATEGY: fetch
  #
  AUTO_DEVOPS_DEV_ENVIRONMENT_NAME: "-dev2"
  AUTO_DEVOPS_PREPROD_ENVIRONMENT_NAME: "-dev2"
  AUTO_DEVOPS_PROD_ENVIRONMENT_NAME: "prod2"
  #
  # To activate the auto release:
  # AUTO_DEVOPS_RELEASE_AUTO: "🔖"
  # AUTO_DEVOPS_PRODUCTION_AUTO: "🚀"
  #
  # To disable quality check jobs:
  # AUTO_DEVOPS_QUALITY_CHECK_DISABLED: "🛑"
  # AUTO_DEVOPS_TEST_DISABLED: "🛑"
  # AUTO_DEVOPS_LINT_DISABLED: "🛑"

#

##############################
# Install
##############################

.autodevops_install:
  stage: Install
  extends:
    - .base_yarn
  interruptible: true

##############################
# Lint
##############################

.autodevops_lint:
  stage: Quality check
  extends:
    - .base_yarn_script
  needs:
    - job: Cache setup
      artifacts: true
  script:
    - yarn lint

##############################
# Test
##############################

.autodevops_test:
  stage: Quality check
  extends:
    - .base_yarn_script
  needs:
    - job: Cache setup
      artifacts: true
  script:
    - yarn test

##############################
# Build
##############################

.autodevops_build:
  stage: Build
  extends:
    - .base_yarn_build_next
  dependencies:
    - Cache setup
    - Lint
    - Test

##############################
# Register
##############################

.autodevops_register_image:
  stage: Registration
  extends:
    - .base_register_stage
  needs:
    - job: Build
      artifacts: true
  variables:
    CONTEXT: .
    IMAGE_NAME: $CI_REGISTRY_IMAGE
    DOCKER_BUILD_ARGS: >-
      --shm-size 512M
    IMAGE_NAME: $CI_REGISTRY_IMAGE/app

##############################
# Notify Deployment Start
##############################

.autodevops_notify_starting_deployment:
  stage: Deploy
  extends:
    - .base_notify_pending_stage
  allow_failure: true

##############################
# Deploy
##############################

.deploy_stage:
  stage: Deploy
  extends:
    - .base_deploy_kosko_stage
  cache:
    key: deploy-${CI_COMMIT_REF_SLUG}
    paths:
      - ${CI_PROJECT_DIR}/dotenv.env
      - ${CI_PROJECT_DIR}/.cache
      - ${K8S_FOLDER}/node_modules
  after_script:
    - echo "CI_ENVIRONMENT_URL=${CI_ENVIRONMENT_URL}" >> dotenv.env

##############################
# Deploy REVIEW
##############################

.autodevops_review:
  extends:
    - .deploy_stage
  variables:
    KOSKO_APPEND_YAML_FROM: .k8s/environments/dev/manifests
    KOSKO_GENERATE_ARGS: >-
      --env dev
  environment:
    auto_stop_in: 1 day
    name: ${CI_COMMIT_REF_NAME}${AUTO_DEVOPS_DEV_ENVIRONMENT_NAME}
    on_stop: Stop review
    url: https://${CI_ENVIRONMENT_SLUG}-${CI_PROJECT_NAME}.${KUBE_INGRESS_BASE_DOMAIN}

##############################
# Deploy PREPROD
##############################

.autodevops_preprod:
  extends:
    - .autodevops_review
  needs:
    - job: Register release
  variables:
    KOSKO_APPEND_YAML_FROM: .k8s/environments/preprod/manifests
    KOSKO_GENERATE_ARGS: >-
      --env preprod
  environment:
    auto_stop_in: 1 week
    name: preprod${AUTO_DEVOPS_PREPROD_ENVIRONMENT_NAME}
    on_stop: Stop preprod
    url: https://preprod-${CI_PROJECT_NAME}.${KUBE_INGRESS_BASE_DOMAIN}

# ##############################
# # Trigger Release
# ##############################

# .autodevops_trigger_release:
#   extends:
#     - .base_trigger_release_stage
#     # - .autodevops_base_rules
#   stage: .post
#   rules:
#     - <<: *rule_on_feature_branch
#       when: always
#     - when: never
#   # rules:
#   #   - <<: *autodevops_global_skip_case
#   #   - <<: *autodevops_on_feature_branch
#   #     when: never
#   #   - <<: *autodevops_on_release
#   #     when: never
#   #   - if: "$CI_COMMIT_TAG"
#   #     when: never
#   #   - if: "$AUTO_DEVOPS_RELEASE_AUTO && $CI_COMMIT_BRANCH == 'master'"
#   #     when: never
#   #   - if: "$AUTO_DEVOPS_RELEASE_AUTO && $CI_COMMIT_MESSAGE !~ /^chore(release): version/"
#   #     when: on_success
#   #   - when: manual

# Trigger release:
#   extends: .autodevops_trigger_release

##############################
# Trigger PRODUCTION
##############################

.autodevops_trigger_production:
  stage: .post
  extends: .base_trigger_production_stage

##############################
# Deploy PRODUCTION
##############################

.autodevops_production:
  extends:
    - .deploy_stage
  variables:
    KOSKO_APPEND_YAML_FROM: .k8s/environments/prod/manifests
    KUBE_NAMESPACE: ${CI_PROJECT_NAME}
    KOSKO_GENERATE_ARGS: >-
      --env prod "!(_*)"
  environment:
    name: ${AUTO_DEVOPS_PROD_ENVIRONMENT_NAME}
    url: https://${CI_PROJECT_NAME}.${KUBE_INGRESS_BASE_DOMAIN}

##############################
# Stop REVIEW
##############################

.autodevops_stop_review:
  extends:
    - .base_docker_kubectl_image_stage
  stage: .post
  environment:
    name: ${CI_COMMIT_REF_NAME}${AUTO_DEVOPS_DEV_ENVIRONMENT_NAME}
    action: stop
  allow_failure: true
  dependencies: []
  variables:
    GIT_STRATEGY: none
  script:
    - echo "kubectl delete namespace ${KUBE_NAMESPACE}"
    - kubectl delete namespace "${KUBE_NAMESPACE}"

##############################
# Stop PREPROD
##############################

.autodevops_stop_preprod:
  extends:
    - .autodevops_stop_review
  environment:
    name: preprod${AUTO_DEVOPS_PREPROD_ENVIRONMENT_NAME}
    action: stop

##############################
# Notify
##############################

.notify:
  dependencies:
    - Notify Start
  allow_failure: true
  cache:
    key: deploy-${CI_COMMIT_REF_SLUG}
    paths:
      - ${CI_PROJECT_DIR}/dotenv.env
    policy: pull
  before_script:
    - |
      set -x

      . dotenv.env

      export HOST=$CI_ENVIRONMENT_URL

##############################
# Notify Fail
##############################

.autodevops_notify_fail:
  stage: .post
  extends:
    - .base_notify_fail_stage
    - .notify

##############################
# Notify Success
##############################

.autodevops_notify_success:
  stage: .post
  extends:
    - .base_notify_success_stage
    - .notify

##############################
# Release
##############################

.autodevops_release:
  extends:
    - .base_semantic_release_stage
  variables:
    GIT_DEPTH: 4242
    SEMANTIC_RELEASE_ARGS: ""
  stage: Release

# Toto:
#   stage: .pre
#   script:
#     - echo PRODUCTION $PRODUCTION
#     - echo RELEASE $RELEASE
#     - printenv | grep
#       -e "^CI_COMMIT_"
#       -e "^CI_ENVIRONMENT_"
#       -e "^CI_PROJECT_"
#       -e "^CI_REGISTRY_"
#       -e "^CI_EXTERNAL_" | sort
