#
# feature-branches deployments
# these jobs interact with the GitHub API to post the deployment URL and status to the pull-request
#

.get_github_id_stage: &get_github_id_stage
  stage: "Prepare"
  image:
    name: ${CI_REGISTRY}/${IMAGE_INFRA_BASE_NAME}/git-deploy:${INFRA_GIT_DEPLOY_VERSION}
  before_script:
    - envsubst < /scripts/get-deploy-id.sh > /scripts/get-github-deploy-id.sh
  script:
    - sh /scripts/get-github-deploy-id.sh
  artifacts:
    paths:
      - github_deploy_id

# do it only on PR
Get Github Id (feature):
  <<: *get_github_id_stage
  environment:
    name: feature-${CLUSTER_NAME}
  except:
    - master
    - /^v.*/

.send_url_to_github_stage: &send_url_to_github_stage
  image:
    name: $CI_REGISTRY/$IMAGE_INFRA_BASE_NAME/docker-kube:latest
  script:
    - export DEPLOY_ID=$(cat github_deploy_id)
    - envsubst < /scripts/send-url.sh > /scripts/send-url-to-github.sh
    - sh /scripts/send-url-to-github.sh

# do it only on PR
Send deployment url to Github (feature):
  <<: *send_url_to_github_stage
  stage: "Send Url to GitHub (feature)"
  before_script:
    - HASH_BRANCH_NAME=$(printf "${CI_COMMIT_REF_NAME}" | sha1sum | cut -c1-5)
    - export INGRESS_ENVIRONMENT_PREFIX=${HASH_BRANCH_NAME}
    - export URL=https://${INGRESS_ENVIRONMENT_PREFIX}.${CI_PROJECT_NAME}.${DOMAIN_NAME}/
  environment:
    name: feature-${CLUSTER_NAME}
  except:
    - master
    - /^v.*/
