.get_github_id_stage: &get_github_id_stage
  stage: "Prepare"
  image:
    name: $CI_REGISTRY/$IMAGE_INFRA_BASE_NAME/docker-kube:latest
    entrypoint: [""]
  before_script:
    - envsubst < k8s/scripts/get-deploy-id.sh > k8s/scripts/get-github-deploy-id.sh
  script:
    - sh k8s/scripts/get-github-deploy-id.sh
  artifacts:
    paths:
      - github_deploy_id
#

Get Github Id (dev):
  <<: *get_github_id_stage
  environment:
    name: $DEV_ENVIRONMENT_NAME
  only:
    - branches
  except:
    - master

Get Github Id (prod):
  <<: *get_github_id_stage
  environment:
    name: $PROD_ENVIRONMENT_NAME
  only:
    - tags

.send_url_to_github_stage: &send_url_to_github_stage
  stage: "Send Url to GitHub"
  image:
    name: $CI_REGISTRY/$IMAGE_INFRA_BASE_NAME/docker-kube:latest
    entrypoint: [""]
  script:
    - export DEPLOY_ID=$(cat github_deploy_id)
    - envsubst < k8s/scripts/send-url.sh > k8s/scripts/send-url-to-github.sh
    - sh k8s/scripts/send-url-to-github.sh $CI_COMMIT_REF_NAME
#

Send deployment url to Github (dev):
  <<: *send_url_to_github_stage
  before_script:
    - HASH_BRANCH_NAME=$(printf "$CI_COMMIT_REF_NAME" | sha1sum | cut -c1-5)
    - export HASH_BRANCH_NAME=$HASH_BRANCH_NAME
    - export URL=http://$HASH_BRANCH_NAME-${CI_PROJECT_NAME}.${CI_ENVIRONMENT_NAME}.social.gouv.fr/
  environment:
    name: $DEV_ENVIRONMENT_NAME
  only:
    - branches
  except:
    - master

Send deployment url to Github (prod):
  <<: *send_url_to_github_stage
  before_script:
    - export URL=http://${CI_PROJECT_NAME}.${CI_ENVIRONMENT_NAME}/
  environment:
    name: $PROD_ENVIRONMENT_NAME
  only:
    - tags
